---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: start service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

- name: Db server setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install Mariadb server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes
    - name: start service
      ansible.builtin.service:
        name: mariadb-server
        state: started
        enabled: yes
