
services:
  db:
    image: mariadb:10.11
    ports:
      - 3306:3306
    entrypoint: ["/entrypoint.sh"]
    command: ["mysqld_safe" , "--datadir=/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    volumes:
      - ./mariadb/entrypoint.sh:/entrypoint.sh
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    entrypoint: ["/entrypoint.sh"]
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - wordpress_data:/var/www/html
      - ./index.html:/srv/html/index.html
    restart: always
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/entrypoint.sh:/entrypoint.sh
    networks:
      - app_network
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    restart: always
    depends_on:
      - db
  

volumes:
  db_data:
  wordpress_data:

networks:
  app_network:
    driver: bridge