---
- name: Install Docker on Ubuntu
  hosts: launched  # Replace with your inventory group or hostname
  become: true

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Execute shell command to add Docker GPG key
      ansible.builtin.shell: |
        apt-get update -y && \
        install -m 0755 -d /etc/apt/keyrings && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
        chmod a+r /etc/apt/keyrings/docker.asc && \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
        apt-get update -y && \
        apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    - name: Add docker group
      group:
        name: docker
        state: present    
    - name: Add user to Docker group
      user:
        name: "ubuntu"
        groups: docker
        append: yes